In [1]:
import csv
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline

In [44]:
pd.set_option('display.precision', 3)

In [3]:
!ls -lhtr

total 13256
drwxr-xr-x   7 tejaswin.p  FKIPL\Domain Users   224B Sep 26 14:48 samples
-rw-r--r--   1 tejaswin.p  FKIPL\Domain Users   4.5K Sep 28 20:44 main.py
-rw-r--r--   1 tejaswin.p  FKIPL\Domain Users   725K Sep 30 11:59 scratchpad.ipynb
-rw-r--r--@  1 tejaswin.p  FKIPL\Domain Users   155K Oct  4 13:30 pymvg-master.zip
drwxr-xr-x@ 14 tejaswin.p  FKIPL\Domain Users   448B Oct  4 13:37 pymvg-master
-rw-r--r--   1 tejaswin.p  FKIPL\Domain Users    51K Oct 12 13:28 projection.ipynb
drwxr-xr-x   9 tejaswin.p  FKIPL\Domain Users   288B Oct 21 14:00 github
-rw-r--r--   1 tejaswin.p  FKIPL\Domain Users   1.8M Oct 24 20:31 books.ipynb
-rw-r--r--   1 tejaswin.p  FKIPL\Domain Users   591K Oct 27 18:34 5pointalgo.ipynb
-rw-r--r--   1 tejaswin.p  FKIPL\Domain Users   842B Nov  4 13:16 py3_shadow_vs_recent_lanes.ipynb
-rw-r--r--   1 tejaswin.p  FKIPL\Domain Users   665K Nov  4 13:17 2019_lanesplit_accuracy.csv
-rw-r--r--   1 tejaswin.p  FKIPL\Domain Users   2.5M Nov  4 13:17 2020_lanesplit_accuracy.csv

In [4]:
df_2019 = pd.read_csv('2019_lanesplit_accuracy.csv')

In [14]:
df_2019.sort_values(['accuracy'], ascending=False, inplace=True)

In [15]:
df_2019.head()

,src_fc,dst_dh,lpe_tier,dg_flag,num_true,num_preds,accuracy
7878,kol_sank_01,2998,REGULAR,False,3,3,1.0
10120,hyderabad_medchal_01,414,REGULAR,True,2,2,1.0
9993,kol_sank_01,305,REGULAR,True,2,2,1.0
9994,kol_sank_01,218,ECONOMY,False,2,2,1.0
9997,blr_wfld,636,ECONOMY,False,2,2,1.0

In [16]:
df_2019[df_2019.num_preds > 200]

,src_fc,dst_dh,lpe_tier,dg_flag,num_true,num_preds,accuracy
77,hyderabad_medchal_01,625,PREMIUM,True,252,252,1.000000
62,binola,52511,EXPRESS,False,271,271,1.000000
103,blr_mal_01,11,PREMIUM,False,230,230,1.000000
98,hyderabad_medchal_01,1513,PREMIUM,False,234,234,1.000000
51,hyderabad_medchal_01,625,PREMIUM,False,285,285,1.000000
128,blr_wfld,52312,EXPRESS,False,213,213,1.000000
87,hyderabad_medchal_01,2593,PREMIUM,False,241,245,0.983673
137,hyderabad_medchal_01,11,REGULAR,True,203,208,0.975962
80,hyderabad_medchal_01,1396,REGULAR,False,236,250,0.944000
127,mum_bndi,159,REGULAR,False,201,213,0.943662
35,binola,151,REGULAR,False,299,318,0.940252
119,hyderabad_medchal_01,2009,REGULAR,False,202,218,0.926606
130,mum_bndi,4961,REGULAR,False,196,212,0.924528
117,chn_tvr_04,285,REGULAR,True,201,219,0.917808
54,ulub_bts,176,REGULAR,False,253,280,0.903571
74,mum_bndi,4963,REGULAR,False,223,252,0.884921
42,frk_bts,298,REGULAR,False,260,301,0.863787
49,blr_wfld,56,REGULAR,False,248,288,0.861111
69,blr_mal_01,137,REGULAR,False,224,261,0.858238
11,kol_sank_01,534,PREMIUM,False,329,384,0.856771
71,hyderabad_medchal_01,381,REGULAR,False,219,256,0.855469
108,blr_mal_01,686,REGULAR,False,195,228,0.855263
107,frk_bts,298,REGULAR,True,193,228,0.846491
0,frk_bts,2995,REGULAR,False,519,614,0.845277
60,blr_wfld,1898,REGULAR,True,229,271,0.845018
41,frk_bts,52517,REGULAR,False,255,302,0.844371
8,blr_wfld,11,REGULAR,False,344,409,0.841076
13,frk_bts,168,REGULAR,False,318,379,0.839050
121,frk_bts,58711,REGULAR,True,181,216,0.837963
132,hyderabad_medchal_01,47,REGULAR,True,175,210,0.833333
...,...,...,...,...,...,...,...
83,ulub_bts,464,REGULAR,False,112,247,0.453441
99,blr_wfld,71263,REGULAR,False,104,232,0.448276
92,frk_bts,1385,REGULAR,True,105,243,0.432099
89,ulub_bts,70706,REGULAR,False,104,244,0.426230
146,ulub_bts,107,ECONOMY,False,86,202,0.425743
102,ulub_bts,1797,REGULAR,False,97,231,0.419913
4,binola,1395,REGULAR,False,197,475,0.414737
25,ulub_bts,618,REGULAR,True,141,343,0.411079
144,ulub_bts,618,REGULAR,False,83,202,0.410891
112,blr_wfld,90,REGULAR,True,89,222,0.400901
16,frk_bts,1385,REGULAR,False,145,366,0.396175
19,binola,1395,REGULAR,True,135,357,0.378151
18,frk_bts,77,REGULAR,False,132,359,0.367688
24,ulub_bts,534,REGULAR,False,126,346,0.364162
32,ulub_bts,162,REGULAR,False,116,327,0.354740
118,ulub_bts,69682,REGULAR,False,76,219,0.347032
45,ulub_bts,533,REGULAR,False,92,293,0.313993
110,ulub_bts,1234,REGULAR,False,70,224,0.312500
31,ulub_bts,1793,REGULAR,False,98,330,0.296970
56,ulub_bts,534,REGULAR,True,75,278,0.269784
120,frk_bts,287,REGULAR,False,56,217,0.258065
59,ulub_bts,71203,REGULAR,False,69,276,0.250000
134,ulub_bts,533,REGULAR,True,52,209,0.248804
84,frk_bts,1395,REGULAR,True,52,247,0.210526
30,ulub_bts,1793,REGULAR,True,70,333,0.210210
91,frk_bts,1394,REGULAR,False,50,243,0.205761
53,frk_bts,1395,REGULAR,False,56,280,0.200000
65,frk_bts,53,REGULAR,False,51,268,0.190299
116,ulub_bts,1346,REGULAR,False,41,219,0.187215
129,frk_bts,53,REGULAR,True,33,213,0.154930

In [17]:
df_2020 = pd.read_csv('2020_lanesplit_accuracy.csv')
df_2020.head()

     src_fc  dst_dh lpe_tier  dg_flag  num_true  num_preds  accuracy
0  ulub_bts     534  PREMIUM     True      1386       1690  0.820118
1  ulub_bts     534  PREMIUM    False      1201       1354  0.887001
2  ulub_bts   81451  PREMIUM     True      1000       1126  0.888099
3  ulub_bts   51625  REGULAR     True       768       1093  0.702653
4  ulub_bts    1798  PREMIUM     True       825       1088  0.758272

In [20]:
df_2020.columns

Index([u'src_fc', u'dst_dh', u'lpe_tier', u'dg_flag', u'num_true',
       u'num_preds', u'accuracy'],
      dtype='object')

## Compare ...

In [74]:
old_rows = df_2019[df_2019.num_preds>=100].shape[0]

In [75]:
merged = pd.merge(df_2019[df_2019.num_preds>=100], df_2020[df_2020.num_preds>=100], 
                how='inner', suffixes=['_2019', '_2020'],
         on=[u'src_fc', u'dst_dh', u'lpe_tier', u'dg_flag'])

In [76]:
print("Overlap 2019 vs 2020: %d/%d"%(merged.shape[0], old_rows)), round(merged.shape[0]*1.0/old_rows, 2)

Overlap 2019 vs 2020: 427/680 0.63

In [77]:
merged['diff'] = merged['accuracy_2019'] - merged['accuracy_2020']

In [78]:
pdrop_rows = len(merged[merged['diff'] > 0])
print("Perf drop 2019 vs 2020: %d/%d"%(pdrop_rows, len(merged))), round(pdrop_rows*1.0/len(merged), 2)

Perf drop 2019 vs 2020: 296/427 0.69

In [79]:
fifty_rows = len(merged[merged['diff'] >= 0.3])
print(">=30%% drop 2019 vs 2020: %d/%d"%(fifty_rows, len(merged))), round(fifty_rows*1.0/len(merged), 2)

>=30% drop 2019 vs 2020: 112/427 0.26

In [80]:
merged[merged['diff']>=0.3].sort_values('diff', ascending=False).head(10).to_csv('topdiff_lanesplit_accuracy.csv', index=False)

In [81]:
!cat topdiff_lanesplit_accuracy.csv

src_fc,dst_dh,lpe_tier,dg_flag,num_true_2019,num_preds_2019,accuracy_2019,num_true_2020,num_preds_2020,accuracy_2020,diff
blr_mal_01,1898,PREMIUM,False,130,130,1.0,0,225,0.0,1.0
blr_mal_01,56983,PREMIUM,False,132,133,0.9924812030075189,3,176,0.017045454545454544,0.9754357484620643
blr_mal_01,11,PREMIUM,False,230,230,1.0,7,181,0.03867403314917127,0.9613259668508287
blr_mal_01,11,PREMIUM,True,134,134,1.0,12,210,0.057142857142857134,0.9428571428571428
hyderabad_medchal_01,2009,REGULAR,True,117,121,0.9669421487603306,37,322,0.11490683229813665,0.8520353164621939
hyderabad_medchal_01,2009,REGULAR,False,202,218,0.9266055045871558,43,402,0.10696517412935323,0.8196403304578026
mum_bndi,255,REGULAR,True,96,103,0.9320388349514565,20,129,0.15503875968992248,0.777000075261534
hyderabad_medchal_01,1332,REGULAR,True,109,110,0.990909090909091,48,195,0.24615384615384614,0.7447552447552448
hyderabad_medchal_01,1332,REGULAR,False,173,181,0.9558011049723756,54,213,0.2535211267605634,0.7022799782118122
binola,168,REGULAR,True,84,108,0.7777777777777778,15,143,0.1048951048951049,0.6728826728826729